### ISSUE TITLE
fatal error: interface_table.h: No such file or directory

### ISSUE THREAD

**Issue by Wenz92** [playerproject/player#19] opened 2020-11-20 16:58 UTC
hello all,
i am installing player-release-3-1-0, during the process by cmake there is an error 
SOFTWARE/player-release-3-1-0/libplayerinterface/interface_util.c:51:10: fatal error: interface_table.h: No such file or directory.

I use system Linux Ubuntu 20.04 LTS.
Thanks a lot

**Comment by dbojadzic** [comment] 2020-12-07 17:19
Same problem here on Ubuntu 18.04 LTS with Cmake Version 3.18.2.

**Comment by ChiragCD** [comment] 2021-01-07 09:38
Hi,

I faced this issue too, I found [this](https://sourceforge.net/p/playerstage/bugs/377/#4d11) helpful. It's also by the author of this repo, so I find it a bit surprising the patch hasn't been merged here. Anyway, this solved the problem for me.

**Comment by richmattes** [comment] 2021-01-08 03:04
It should already be merged in to `master`, but I don't think there has been a release since then.  Can you confirm that the git `master` branch doesn't have this issue?

**Comment by ChiragCD** [comment] 2021-01-08 07:59
Apologies, Rich, the patch has indeed been merged. I faced the issue as I had downloaded the release, and not cloned this repo. You seem to have implemented the change already.

Cheers!

**Comment by richmattes** [comment] 2021-08-06 02:20
Confirmed issue is fixed in `master`, closing.

**Closed by richmattes** 2021-08-06 02:20 UTC
